SKT-5:Configures to use environment variable using the .env file(new PR)
leapfrogtechnology/nestjs-starter-kit pull request #4
Opened 2022-05-20 12:08 UTC by prasharma0

**Summary**
-This PR Configures to use environment variable using the .env file

**Description**
-Installed the dependency using the following command: $ npm i --save @nestjs/config
-To have a clean project structure, create a new folder called common.
-Created ENV directory for various modes of operations. 
-Reconfigured the nest-cli.json file in order to have the environment files in our dist/ folder, we need to add a compiler rule to our nest-cli.json.
-Created a helper directory inside which the env.helper.ts file, created a function that returns the absolute path to our environment file based on our NODE_ENV, where it has two fallbacks. The first one is if the NODE_ENV is not set then the absolute path of the development.env file is what we try to get Secondly if the file does not exist, then return the absolute path to the .env file.
-After the environment files and the helper files get created, added the ConfigModule in the app.module.ts globally which means we do not have to import it every time we need to access the ConfigService.
-Finally modify the app.service.ts, where ConfigService gets injected so that you can check the database name.

2022-05-22 02:55 UTC, bmnepali requested changes

2022-05-22 02:55 UTC, bmnepali commented on package.json
> +    "test:watch": "jest --watch",
There is one extra space here in this line.

2022-05-22 02:55 UTC, bmnepali commented on Dockerfile
>  CMD ["node", "dist/main"]
You need an extra empty line to the end of the file.

2022-05-22 02:55 UTC, bmnepali commented on .gitignore
> +**/production.env
You need an extra empty line to the end of the file.

2022-05-24 02:34 UTC, bmnepali approved these changes

2022-05-24 04:10 UTC, RobusGauli requested changes

2022-05-24 04:10 UTC, RobusGauli commented on .gitignore
> +#.env
`# Environment variables` would be a better name.

2022-05-24 04:10 UTC, RobusGauli commented on .gitignore
> +**/development.env
Always use .env.* for environment variables and not the other way around. You environment variable file should start with something like this 

`.env.development`, `.env.production` ...
This way your .gitignore would be simple as well.  (.env*)

2022-05-24 05:02 UTC, RobusGauli requested changes

2022-05-24 05:02 UTC, RobusGauli commented on src/app.module.ts
> +const envFilePath: string = getEnvPath(`${__dirname}/common/envs`);
Don't hard code this character `/`. This depends on the OS (linux/windows/BSD...). Use `path.join` for resolving path.

2022-05-24 05:02 UTC, RobusGauli commented on src/app.service.ts
> +    console.log({ databaseName });
Remove this? Don't think it's necessary.

2022-05-24 05:02 UTC, RobusGauli commented on src/common/helper/env.helper.ts
> +  const filename: string = env ? `${env}.env` : 'development.env';
I need you need to fix this? Because now environment file starts with .env.{environment} name?

2022-05-24 05:02 UTC, RobusGauli commented on src/common/helper/env.helper.ts
> +  const fallback: string = resolve(`${val}/.env`);
Let's not have a fallback. Exit the process with non-zero status code with appropriate error log in stderr.

2022-05-26 07:58 UTC, iampujan approved these changes

2022-05-26 08:07 UTC, bhuwantm commented
It would have been better to separate out the commit for pull request template file and prettier config files.

2022-05-27 04:18 UTC, bhuwantm commented on src/app.module.ts
> +const path = require('path');
better use import?
import * as path from 'path'

2022-05-27 04:18 UTC, bhuwantm commented on src/app.module.ts
> +);
leave a line

2022-05-27 04:18 UTC, bhuwantm commented on package.json
> +    "format": "prettier --check --ignore-path .gitignore .",
use of .prettierignore like .gitignore file will be better

2022-05-30 06:52 UTC, bhuwantm approved these changes

2022-05-30 07:53 UTC, merged