SKT-6: Implementation of Middleware in NestJS
leapfrogtechnology/nestjs-starter-kit pull request #5
Opened 2022-06-01 09:32 UTC by prasharma0

**Summary**
Implementation of Middleware in NestJS 

**Description**
-Created a middleware using the class method where we can log the headers that were requested.
-Created a controller where we can define our routes using the Get request only for the illustration purpose that returns a specific value that can be seen while using the app. This also works for globalizing the route using the .forRoutes("*").
-While in the AppModule class, applied the middleware for the used controller using the wildcard path available and including all the HTTP request methods.
-Additionally, We can also implement using the business logic of API  by testing purposes as shown below:
         if(req.headers["api_token"]!== "my_token") {
         throw new BadRequestException("Invalid Token !");
    }
Here, we are passing the payload in order to validate the token in our middleware.

2022-06-02 04:33 UTC, bmnepali requested changes

2022-06-02 04:33 UTC, bmnepali commented on src/common/middleware/apitoken.ts
> +    console.log(req.headers);
Use the `Logger` class for logging instead.

2022-06-02 04:33 UTC, bmnepali commented on src/app.module.ts
> +    consumer.apply(ApiToken).forRoutes({ path: "*", method: RequestMethod.ALL });
Looks like you are applying the middle for all paths, even for the login paths. I think you will have to apply the middleware for the paths in `AppController`. Please check.

2022-06-13 11:51 UTC, bhuwantm commented
### Formatting Problems
There seems to be too many formatting problems, better format the code with prettier before commiting the files. Alternatively if you are using vscode you can use formatOnSave feature for automatic code formatting on each save.


### Module Separation
Separating out the codes as per module. Create a *.module.ts file for each module and load those modules. This will be better approach instead of loading controller and service for each module in main module.


### Code Structuring
Structure out for code properly, try to follow a fix pattern. For example in your PR you are using you are creating login.module.ts in middleware folder.


### Verbosity
Variable naming should be verbose so that its easier for other developer to understand. For example in your case you are using Logging for authenticating the token. If its for authentication you could have named the middleware as "authentication".


### Logical Separation
Separate out logic for Authentication, Logging, HomeLogging etc. In your PR you are checking for token in both Loggin and HomeLogging middleware. Instead of this each middleware should have specific purpose and you could chain it like:
`consumer.apply(cors(), helmet(), logger)`

For reference: [Multiple Middleware](https://docs.nestjs.com/middleware#multiple-middleware)

### Naming Convention
Its not necessary but its better to follow naming convention. For example in your PR you are naming class as homeLogger instead of HomeLogger

2022-06-13 11:55 UTC, bhuwantm requested changes

2022-06-13 11:55 UTC, bhuwantm commented on src/common/middleware/auth.ts
> +export class Logger implements NestMiddleware {
Is this suppose to be authentication middleware or is it meant for loggin request.
If its for authentication, name it accordingly.

2022-06-13 11:55 UTC, bhuwantm commented on src/common/middleware/auth.ts
> +    if(req.headers["api_token"] === "my_token"){
If the token is supposed to be auth token, then its better to use Authorization header.

2022-06-13 11:55 UTC, bhuwantm commented on src/common/middleware/home.ts
> +export class homeLogger implements NestMiddleware {
Again if this is for logging the request to home page, remove the token checking mechanism.

2022-06-13 11:55 UTC, bhuwantm commented on src/common/middleware/login.module.ts
> +        consumer.apply(homeLogger).forRoutes({ path: "/", method: RequestMethod.POST });
Is the homeLogger middleware for post request only?

2022-06-13 11:58 UTC, bhuwantm commented
Also we dont need too many module for starter kit, just a single module with appropriate structure and flow will enough.

2022-06-15 05:47 UTC, bhuwantm requested changes

2022-06-15 05:47 UTC, bhuwantm commented on src/common/users/users.controller.ts
>    }
leave a new line here

2022-06-15 05:47 UTC, bhuwantm commented on src/common/users/middleware/specificMiddleware.ts
> +}
rename the file to specificLogger.middleware.ts

2022-06-16 04:45 UTC, bhuwantm approved these changes

2022-06-17 04:16 UTC, iampujan approved these changes

2022-06-17 06:58 UTC, merged